### ISSUE TITLE
Cannot install on OMV 5 -- Missing migration

### ISSUE THREAD

**Issue by skarekrow** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#27]
Hello,

I was in the process of moving this machine from 4 to 5, and the snapraid plugin seems unable to install. For some reason I don't get much output on the _why_ it's failing, any ideas?:
```
Preparing to unpack .../openmediavault-snapraid_5.0.5_all.deb ...
Unpacking openmediavault-snapraid (5.0.5) ...
Setting up openmediavault-snapraid (5.0.5) ...
Updating configuration database ...
dpkg: error processing package openmediavault-snapraid (--configure):
 installed openmediavault-snapraid package post-installation script subprocess returned error exit status 1
Processing triggers for rsyslog (8.1901.0-1) ...
Processing triggers for openmediavault (5.5.3-1) ...
Updating locale files ...
Updating file permissions ...
Purging internal cache ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-snapraid
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by ryecoaaron** [comment]
What is the output of:
dpkg -l | grep openm
omv-salt deploy run snapraid

**Comment by skarekrow** [comment]
Hey Aaron, here's the info:
```
root@isengard:~# dpkg -l | grep openm
ii  libopenmpt0:amd64                    0.4.3-1                              amd64        module music library based on OpenMPT -- shared library
ii  omvextras-unionbackend               5.0.2                                all          union filesystems backend plugin for openmediavault
ii  openmediavault                       5.5.3-1                              all          openmediavault - The open network attached storage solution
ii  openmediavault-backup                5.2                                  all          backup plugin for OpenMediaVault.
ii  openmediavault-diskstats             5.0.5-1                              all          openmediavault disk monitoring plugin
ii  openmediavault-downloader            5.1                                  all          OpenMediaVault downloader plugin
ic  openmediavault-flashmemory           4.2.1                                all          folder2ram plugin for OpenMediaVault
ii  openmediavault-keyring               1.0                                  all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-lvm2                  5.0.2-1                              all          openmediavault Logical Volume Manager (LVM2) plugin
ii  openmediavault-minidlna              5.0.4                                all          OpenMediaVault miniDLNA (DLNA server) plugin
ii  openmediavault-omvextrasorg          5.3.4                                all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-sftp                  5.0.6                                all          sftp server
iF  openmediavault-snapraid              5.0.5                                all          snapraid plugin for OpenMediaVault.
ii  openmediavault-unionfilesystems      5.1.2                                all          Union filesystems plugin for OpenMediaVault.
root@isengard:~# omv-salt deploy run snapraid
isengard.home.lan:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.snapraid.default' failed: Jinja error: The property 'rules.rule.0.rule-folder' does not exist in the model 'conf.service.snapraid'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 400, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 18, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 39, in get
    objs = db.get(id_, identifier)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 712, in execute
    self._response = self._elements_to_object(elements)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 473, in _elements_to_object
    result.set_dict(self._element_to_dict(elements[0]), False)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 207, in set_dict
    self.set(key, value, validate)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 181, in set
    self.assert_exists(name)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 153, in assert_exists
    % (name, self.model.id)
openmediavault.exceptions.AssertException: The property 'rules.rule.0.rule-folder' does not exist in the model 'conf.service.snapraid'.

; line 18

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

{% set config = salt['omv_conf.get']('conf.service.snapraid') %}    <======================

configure_snapraid:
  file.managed:
    - name: "/etc/snapraid.conf"
    - source:
[...]
---
```

**Comment by ryecoaaron** [comment]
I'm not sure why I didn't create a migration scrip for this plugin.  Do the following:

sudo sed -i "s/rule-folder/rulefolder/g" /etc/openmediavault/config.xml
sudo apt-get -f install

**Comment by skarekrow** [comment]
That did it, thanks @ryecoaaron!

**Comment by skarekrow** [comment]
Closed by https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/commit/3edb0728dc63c97d790756ed2e2ce516a706578e
