### ISSUE TITLE
Broken update?

### ISSUE THREAD

**Issue by Alex-Jr** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#47]
Hey there, 
I just updated the snapraid plugin and now i can't see any information about my array using the SnapRAID tab in OMV GUI.
I have not changed any config before or after the update

```
Invalid RPC response. Please check the syslog for more information.

OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(95): OMV\Rpc\Rpc::call()
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}
```

I found that the updated from 7.0.7 to 7.0.8 maybe have failed

```
Setting up openmediavault-snapraid (7.0.8) ...
Updating configuration database ...
  Running migration conf.service.snapraid_7.0.7
/usr/share/openmediavault/confdb/migrations.d/conf.service.snapraid_7.0.7.sh: 12: [: -eq: unexpected operator
/usr/share/openmediavault/confdb/migrations.d/conf.service.snapraid_7.0.7.sh: 12: [: -eq: unexpected operator
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 18, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 41, in get
    objs = db.get(id_, identifier)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 735, in execute
    self._response = self._elements_to_object(elements)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 493, in _elements_to_object
    result.validate()
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 236, in validate
    self.model.validate(self.get_dict())
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 202, in validate
    self.schema.validate(data)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 175, in validate
    self._validate_type(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 230, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 201, in _validate_type
    self._validate_object(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 306, in _validate_object
    self._check_properties(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 521, in _check_properties
    self._validate_type(value[propk], propv, path)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 230, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 201, in _validate_type
    self._validate_object(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 306, in _validate_object
    self._check_properties(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 521, in _check_properties
    self._validate_type(value[propk], propv, path)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 230, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 195, in _validate_type
    self._validate_array(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 297, in _validate_array
    self._check_items(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 549, in _check_items
    self._validate_type(itemv, schema['items'], path)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 230, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 201, in _validate_type
    self._validate_object(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 301, in _validate_object
    raise SchemaValidationException(
openmediavault.json.schema.SchemaValidationException: drives.drive[0]: The value 'paritynum' is not an object.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 219, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 523, in render_jinja_tmpl
    raise SaltRenderError(
salt.exceptions.SaltRenderError: Jinja error: drives.drive[0]: The value 'paritynum' is not an object.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 18, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 41, in get
    objs = db.get(id_, identifier)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 735, in execute
    self._response = self._elements_to_object(elements)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 493, in _elements_to_object
    result.validate()
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 236, in validate
    self.model.validate(self.get_dict())
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 202, in validate
    self.schema.validate(data)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 175, in validate
    self._validate_type(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 230, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 201, in _validate_type
    self._validate_object(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 306, in _validate_object
    self._check_properties(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 521, in _check_properties
    self._validate_type(value[propk], propv, path)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 230, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 201, in _validate_type
    self._validate_object(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 306, in _validate_object
    self._check_properties(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 521, in _check_properties
    self._validate_type(value[propk], propv, path)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 230, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 195, in _validate_type
    self._validate_array(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 297, in _validate_array
    self._check_items(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 549, in _check_items
    self._validate_type(itemv, schema['items'], path)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 230, in _validate_type
    raise last_exception
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 201, in _validate_type
    self._validate_object(value, schema, name)
  File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 301, in _validate_object
    raise SchemaValidationException(
openmediavault.json.schema.SchemaValidationException: drives.drive[0]: The value 'paritynum' is not an object.

; line 18

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

{% set config = salt['omv_conf.get']('conf.service.snapraid') %}    <======================
{% set confDir = '/etc/snapraid' %}
{% set confPrefix = 'omv-snapraid-' %}

configure_snapraid_envvar_dir:
  file.directory:
[...]
```

**Comment by ryecoaaron** [comment]
The 7.0.7 update broke the snapraid database entries for the non-parity disks.  So, you either need to restore the snapraid section of the database from backup or uninstall the plugin and reinstall and recreate the array.  There isn't any way I can have the plugin restore the lost entries due to a typo.

**Comment by ryecoaaron** [comment]
https://forum.openmediavault.org/index.php?thread/52232-snapraid-7-0-7-wiping-drive-config-on-upgrade/

**Comment by Alex-Jr** [comment]
Thanks for your help. Next time I search in the forum before opening an issue
